[package]
name = "main"
version = "0.1.0"
edition = "2024"
authors = ["Muhammad Waleed Khan <waleedjaved911@gmail.com>"]

[dependencies]
anyhow="1.0.98"
clap = { version ="4.5.40", features=["derive"] }
encryptor = { path = "../encryptor" }